// Centralise toutes les icônes utilisées dans WakeRef
import {
  IconAlertTriangle,
  IconMicrophone,
  IconPlayerStopFilled,
  IconArrowBackUp,
  IconArrowDownFromArc,
  IconArrowLeft,
  IconArrowRight,
  IconArrowLoopRight,
  IconArrowUp,
  IconArrowZigZag,
  IconArrowsExchange,
  IconArrowsUp,
  IconBrandInstagram,
  IconBrandYoutube,
  IconBinaryTree,
  IconBulb,
  IconCalculator,
  IconCheck,
  IconChevronRight,
  IconCloudUpload,
  IconConfetti,
  IconCopy,
  IconDeviceGamepad2,
  IconEscalator,
  IconEscalatorUp,
  IconExternalLink,
  IconEyeOff,
  IconFileDescription,
  IconFlag,
  IconFlipHorizontal,
  IconHandGrab,
  IconHelp,
  IconHome,
  IconInbox,
  IconInfoCircle,
  IconLayoutDashboard,
  IconLink,
  IconList,
  IconLoader2,
  IconLock,
  IconLogout,
  IconMail,
  IconMenu2,
  IconMinus,
  IconMoon,
  IconPencil,
  IconPlayerPlay,
  IconPlus,
  IconRefresh,
  IconRipple,
  IconRotate,
  IconRotate2,
  IconRotate360,
  IconRotateClockwise,
  IconRotateClockwise2,
  IconSearch,
  IconSend,
  IconShare3,
  IconStar,
  IconSun,
  IconTrash,
  IconUpload,
  IconVideo,
  IconVideoOff,
  IconX,
} from '@tabler/icons-react'

const ICONS = {
  'alert-triangle':         IconAlertTriangle,
  'mic':                    IconMicrophone,
  'player-stop':            IconPlayerStopFilled,
  'arrow-back-up':          IconArrowBackUp,
  'arrow-down-from-arc':    IconArrowDownFromArc,
  'arrow-left':             IconArrowLeft,
  'arrow-right':            IconArrowRight,
  'arrow-loop-right':       IconArrowLoopRight,
  'arrow-up':               IconArrowUp,
  'arrow-zig-zag':          IconArrowZigZag,
  'arrows-exchange':        IconArrowsExchange,
  'arrows-up':              IconArrowsUp,
  'brand-instagram':        IconBrandInstagram,
  'brand-youtube':          IconBrandYoutube,
  'binary-tree':            IconBinaryTree,
  'bulb':                   IconBulb,
  'calculator':             IconCalculator,
  'check':                  IconCheck,
  'chevron-right':          IconChevronRight,
  'cloud-upload':           IconCloudUpload,
  'confetti':               IconConfetti,
  'copy':                   IconCopy,
  'device-gamepad-2':       IconDeviceGamepad2,
  'escalator':              IconEscalator,
  'escalator-up':           IconEscalatorUp,
  'external-link':          IconExternalLink,
  'eye-off':                IconEyeOff,
  'file-description':       IconFileDescription,
  'flag':                   IconFlag,
  'flip-horizontal':        IconFlipHorizontal,
  'hand-grab':              IconHandGrab,
  'help':                   IconHelp,
  'home':                   IconHome,
  'inbox':                  IconInbox,
  'info-circle':            IconInfoCircle,
  'layout-dashboard':       IconLayoutDashboard,
  'link':                   IconLink,
  'list':                   IconList,
  'loader-2':               IconLoader2,
  'lock':                   IconLock,
  'logout':                 IconLogout,
  'mail':                   IconMail,
  'menu-2':                   IconMenu2,
  'minus':                  IconMinus,
  'moon':                   IconMoon,
  'pencil':                 IconPencil,
  'player-play':            IconPlayerPlay,
  'plus':                   IconPlus,
  'refresh':                IconRefresh,
  'ripple':                 IconRipple,
  'rotate':                 IconRotate,
  'rotate-2':               IconRotate2,
  'rotate-2-clockwise':     IconRotateClockwise2,
  'rotate-360':             IconRotate360,
  'rotate-clockwise':       IconRotateClockwise,
  'rotate-clockwise-2':     IconRotateClockwise2,
  'search':                 IconSearch,
  'send':                   IconSend,
  'share-3':                IconShare3,
  'star':                   IconStar,
  'sun':                    IconSun,
  'trash':                  IconTrash,
  'upload':                 IconUpload,
  'video':                  IconVideo,
  'video-off':              IconVideoOff,
  'x':                      IconX,
}

export default function Icon({ name, size = 18, style, className, label }) {
  const Component = ICONS[name]
  if (!Component) {
    console.warn(`Icon "${name}" not found`)
    return null
  }
  // Par défaut décoratif (masqué aux lecteurs d'écran). Passer `label` pour
  // une icône porteuse de sens (ex. icône seule dans un lien).
  const a11y = label
    ? { role: 'img', 'aria-label': label }
    : { 'aria-hidden': true, focusable: false }
  return <Component size={size} style={style} className={className} {...a11y} />
}
