// Centralise toutes les icônes utilisées dans WakeRef
import {
  IconArrowBackUp,
  IconArrowDownFromArc,
  IconArrowLeft,
  IconArrowRight,
  IconArrowLoopRight,
  IconArrowUp,
  IconArrowZigZag,
  IconArrowsExchange,
  IconArrowsUp,
  IconBrandInstagram,
  IconBrandYoutube,
  IconBulb,
  IconCheck,
  IconChevronRight,
  IconConfetti,
  IconEdit,
  IconEscalator,
  IconEscalatorUp,
  IconExternalLink,
  IconEyeOff,
  IconFileDescription,
  IconFlag,
  IconFlipHorizontal,
  IconHandGrab,
  IconHelp,
  IconHome,
  IconInfoCircle,
  IconLayoutDashboard,
  IconLink,
  IconList,
  IconLoader2,
  IconLock,
  IconLogout,
  IconMail,
  IconMinus,
  IconPencil,
  IconPlayerPlay,
  IconPlus,
  IconRefresh,
  IconRipple,
  IconRotate2,
  IconRotateClockwise,
  IconRotateClockwise2,
  IconSearch,
  IconSend,
  IconStar,
  IconTrash,
  IconUpload,
  IconVideo,
  IconVideoOff,
  IconWaveSine,
  IconX,
  IconVideoPlus,
  IconSun,
  IconMoon,
} from '@tabler/icons-react'

const ICONS = {
  'arrow-back-up':          IconArrowBackUp,
  'arrow-down-from-arc':    IconArrowDownFromArc,
  'arrow-left':             IconArrowLeft,
  'arrow-right':            IconArrowRight,
  'arrow-loop-right':       IconArrowLoopRight,
  'arrow-up':               IconArrowUp,
  'arrow-zig-zag':          IconArrowZigZag,
  'arrows-exchange':        IconArrowsExchange,
  'arrows-up':              IconArrowsUp,
  'brand-instagram':        IconBrandInstagram,
  'brand-youtube':          IconBrandYoutube,
  'bulb':                   IconBulb,
  'check':                  IconCheck,
  'chevron-right':          IconChevronRight,
  'confetti':               IconConfetti,
  'edit':                   IconEdit,
  'escalator':              IconEscalator,
  'escalator-up':           IconEscalatorUp,
  'external-link':          IconExternalLink,
  'eye-off':                IconEyeOff,
  'file-description':       IconFileDescription,
  'flag':                   IconFlag,
  'flip-horizontal':        IconFlipHorizontal,
  'hand-grab':              IconHandGrab,
  'help':                   IconHelp,
  'home':                   IconHome,
  'info-circle':            IconInfoCircle,
  'layout-dashboard':       IconLayoutDashboard,
  'link':                   IconLink,
  'list':                   IconList,
  'loader-2':               IconLoader2,
  'lock':                   IconLock,
  'logout':                 IconLogout,
  'mail':                   IconMail,
  'minus':                  IconMinus,
  'pencil':                 IconPencil,
  'player-play':            IconPlayerPlay,
  'plus':                   IconPlus,
  'refresh':                IconRefresh,
  'ripple':                 IconRipple,
  'rotate-2':               IconRotate2,
  'rotate-clockwise':       IconRotateClockwise,
  'rotate-clockwise-2':     IconRotateClockwise2,
  'search':                 IconSearch,
  'send':                   IconSend,
  'star':                   IconStar,
  'trash':                  IconTrash,
  'upload':                 IconUpload,
  'video':                  IconVideo,
  'video-off':              IconVideoOff,
  'video-plus':             IconVideoPlus,
  'wave-sine':              IconWaveSine,
  'x':                      IconX,
  'sun':                    IconSun,
  'moon':                   IconMoon,
}

export default function Icon({ name, size = 18, style, className }) {
  const Component = ICONS[name]
  if (!Component) {
    console.warn(`Icon "${name}" not found`)
    return null
  }
  return <Component size={size} style={style} className={className} />
}
